name: Python Folder and File Validator

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Run folder and file check script
      run: |
        python range_file_validator.py
